import { useState } from "react";
import type { Metrics } from "../data";
import { formatCount, formatDate, formatNumber } from "../format";
import { linkTo } from "../router";

const TABS = [
  { path: "/", label: "Slate" },
  { path: "/players", label: "Players" },
  { path: "/lab", label: "Model Lab" },
  { path: "/methodology", label: "Methodology" },
];

function isActive(tabPath: string, currentPath: string): boolean {
  return tabPath === "/"
    ? currentPath === "/"
    : currentPath.startsWith(tabPath);
}

function currentTheme(): "light" | "dark" {
  const chosen = document.documentElement.dataset.theme;
  if (chosen === "light" || chosen === "dark") return chosen;
  return window.matchMedia("(prefers-color-scheme: dark)").matches
    ? "dark"
    : "light";
}

function ThemeToggle() {
  const [theme, setTheme] = useState(currentTheme);
  const toggle = () => {
    const next = theme === "dark" ? "light" : "dark";
    document.documentElement.dataset.theme = next;
    try {
      localStorage.setItem("hardwood-theme", next);
    } catch {
      // Private browsing can block storage; the theme still applies for this visit.
    }
    setTheme(next);
  };
  return (
    <button
      type="button"
      className="theme-toggle"
      onClick={toggle}
      aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} theme`}
    >
      <svg viewBox="0 0 16 16" aria-hidden="true">
        <circle
          cx="8"
          cy="8"
          r="6.25"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.5"
        />
        <path d="M8 1.75a6.25 6.25 0 0 1 0 12.5z" fill="currentColor" />
      </svg>
    </button>
  );
}

// The ensemble is the projection the app shows, chosen on the validation season.
export function modelError(metrics: Metrics): number {
  return metrics.leaderboard.find((entry) => entry.key === "ensemble")!.test
    .mae;
}

export function TopBar({
  path,
  metrics,
}: {
  path: string;
  metrics: Metrics | null;
}) {
  return (
    <header className="top-bar">
      <div className="top-bar-inner">
        <a className="wordmark" href={linkTo("/")}>
          Hardwood
        </a>
        <nav className="tabs" aria-label="Sections">
          {TABS.map((tab) => (
            <a
              key={tab.path}
              href={linkTo(tab.path)}
              aria-current={isActive(tab.path, path) ? "page" : undefined}
            >
              {tab.label}
            </a>
          ))}
        </nav>
        {metrics && (
          <a
            className="model-stamp figure"
            href={linkTo("/methodology")}
            title="How the models were trained and tested"
          >
            <span>
              trained through {formatDate(metrics.data.trained_through)}
            </span>
            <span>{formatCount(metrics.data.fit_rows)} player-games</span>
            <span>test MAE {formatNumber(modelError(metrics), 2)} FP</span>
          </a>
        )}
        <ThemeToggle />
      </div>
    </header>
  );
}

export function Footer({ metrics }: { metrics: Metrics }) {
  return (
    <footer className="footer">
      <p>
        Projections are generated by Random Forest and XGBoost models trained on{" "}
        {formatCount(metrics.data.fit_rows)} player-games through{" "}
        {formatDate(metrics.data.trained_through)}. On the{" "}
        {metrics.data.test_season} season, which the models never saw, the
        average miss was {formatNumber(modelError(metrics), 2)} fantasy points.{" "}
        <a href={linkTo("/methodology")}>How it works</a>
      </p>
      <p>
        Box scores from stats.nba.com. DraftKings scoring. Not affiliated with
        the NBA or DraftKings.
      </p>
    </footer>
  );
}
